name: Download Models from Google Drive

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  download-files:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Create credentials.json file from the GitHub secret
      - name: Create credentials.json from secret
        run: echo "${{ secrets.GDRIVE_CREDENTIALS }}" > credentials.json

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: pip install google-auth google-auth-httplib2 google-api-python-client

      # Step 5: Download files using the Python script
      - name: Run download_google_drive.py
        run: |
          python download_google_drive.py
