name: Download Google Drive Files

# Triggers the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  download-files:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Create the credentials.json file from the GitHub secret
      - name: Create credentials.json file from secret
        run: echo "${{ secrets.GDRIVE_CREDENTIALS }}" > credentials.json

      # Step 3: Install the required dependencies
      - name: Install dependencies
        run: pip install google-auth google-auth-httplib2 google-api-python-client

      # Step 4: Run the Python script to download the file from Google Drive
      - name: Download a file from Google Drive
        run: |
          python download_google_drive.py
